### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ykws** [ykws/hubot-animemap#1]
```javascript
2016-11-08T15:09:48.760281+00:00 app[web.1]: 
2016-11-08T15:20:11.541659+00:00 app[web.1]: [Tue Nov 08 2016 15:20:11 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'length' of undefined
2016-11-08T15:20:11.541671+00:00 app[web.1]:   at AnimeMap.allParse (/app/node_modules/hubot-animemap/animemap.coffee:62:5, <js>:69:30)
2016-11-08T15:20:11.541672+00:00 app[web.1]:   at AnimeMap.parse (/app/node_modules/hubot-animemap/animemap.coffee:46:14, <js>:45:25)
2016-11-08T15:20:11.541673+00:00 app[web.1]:   at AnimeMap.getPrefList (/app/node_modules/hubot-animemap/animemap.coffee:40:12, <js>:38:20)
2016-11-08T15:20:11.541675+00:00 app[web.1]:   at /app/node_modules/hubot-animemap/animemap.coffee:83:17, <js>:99:26
2016-11-08T15:20:11.541676+00:00 app[web.1]:   at IncomingMessage.<anonymous> (/app/node_modules/hubot/node_modules/scoped-http-client/src/index.js:95:22)
2016-11-08T15:20:11.541677+00:00 app[web.1]:   at IncomingMessage.emit (events.js:117:20)
2016-11-08T15:20:11.541678+00:00 app[web.1]:   at _stream_readable.js:944:16
2016-11-08T15:20:11.541679+00:00 app[web.1]:   at process._tickCallback (node.js:458:13)
2016-11-08T15:20:11.541681+00:00 app[web.1]: 
```

**Comment by ykws** [comment]
Dead source service...
http://animemap.net/pages/api/
